industry_categories = {
    "ELECTRONICS_SHOP": "Electronics / Technology",
    "TECH_SHOP": "Electronics / Technology",
    "HIPSTER_ELECTRONICS_SHOP": "Electronics / Technology",
    "CHINESE_RESTAURANT": "Dining",
    "TAKEAWAY": "Dining",
    "SEAFOOD_RESAURANT": "Dining",
    "CHINESE_TAKEAWAY": "Dining",
    "TAKEAWAY_CURRY": "Dining",
    "STEAK_HOUSE": "Dining",
    "RESTAURANT": "Dining",
    "LOCAL_PUB": "Dining",
    "INDIAN_RESTAURANT": "Dining",
    "A_SUPERMARKET": "Supermarkets",
    "EXPRESS_SUPERMARKET": "Supermarkets",
    "THE_SUPERMARKET": "Supermarkets",
    "LARGE_SUPERMARKET": "Supermarkets",
    "CLOTHES_SHOP": "Apparel",
    "DEPARTMENT_STORE": "Apparel",
    "FASHION_SHOP": "Apparel",
    "FASHIONABLE_SPORTSWARE_SHOP": "Sports",
    "TRAINER_SHOP": "Sports",
    "SPORT_SHOP": "Sports",
    "RUNNING_SHOP": "Sports",
    "VIDEO_GAME_STORE": "Gaming",
    "GAME_SHOP": "Gaming",
    "TOY_SHOP": "Children",
    "KIDS_CLOTHING_SHOP": "Children",
    "KIDS_ACTIVITY_CENTRE": "Children",
    "CHILDRENDS_SHOP": "Children",
    "SCHOOL_SUPPLY_STORE": "Children",
    "HOME_IMPROVEMENT_STORE": "Hardware",
    "DIY_STORE": "Hardware",
    "PET_TOY_SHOP": "Pets",
    "PET_SHOP": "Pets",
    "WE_HAVE_BEAN_WEIGHTING": "Coffee Beans and Teas",
    "TO_BEAN_OR_NOT_TO_BEAN": "Coffee Beans and Teas",
    "TEA_SHOP": "Coffee Beans and Teas",
    "ROASTERIE": "Coffee Beans and Teas",
    "RESTAURANT_VOUCHER": "Gifts",
    "FLORIST": "Gifts",
    "BUTCHER": "Specialty Foods",
    "GREENGROCER": "Specialty Foods",
    "BUTCHERS": "Specialty Foods",
    "TURKEY_FARM": "Specialty Foods",
    "COOKSHOP": "Specialty Foods",
    "JEWLLERY_SHOP": "Accessories",
    "ACCESSORY_SHOP": "Accessories",
    "GYM": "Health and fitness",
    "LIQUORE_STORE": "Alcohol",
    "WHISKEY_SHOP": "Alcohol",
    "WINE_CELLAR": "Alcohol",
    "LOCAL_BOOKSHOP": "Books",
    "BOOKSHOP": "Books",
    "SECOND_HAND_BOOKSHOP": "Books",
    "COMIC_BOOK_SHOP": "Books",
    "NERDY_BOOK_STORE": "Books",
    "WINE_BAR": "Pubs / Bars",
    "WHISKEY_BAR": "Pubs / Bars",
    "PUB": "Pubs / Bars",
    "G&T_BAR": "Pubs / Bars",
    "COCKTAIL_BAR": "Pubs / Bars",
    "LOCAL_WATERING_HOLE": "Pubs / Bars",
    "BAR": "Pubs / Bars",
    "STREAMING_SERVICE": "TV/Film",
    "DVD_SHOP": "TV/Film",
    "CINEMA": "TV/Film",
    "LOCAL_RESTAURANT": "Lunch / Light Meal",
    "SANDWICH_SHOP": "Lunch / Light Meal",
    "LUNCH_VAN": "Lunch / Light Meal",
    "LUNCH_PLACE": "Lunch / Light Meal",
    "KEBAB_SHOP": "Lunch / Light Meal",
    "CAFE": "Lunch / Light Meal",
    "A_CAFE": "Cafes",
    "A_LOCAL_COFFEE_SHOP": "Cafes",
    "CAFÉ": "Cafes",
    "COFFEE_SHOP": "Cafes",
    "GOURMET_COFFEE_SHOP": "Cafes",
    "TOTALLY_A_REAL_COFFEE_SHOP": "Cafes",
    "PRETENTIOUS_COFFEE_SHOP": "Cafes",
    "HIPSTER_COFFEE_SHOP": "Cafes"
}