# Industry Mapping
industry_categories = {
    'topshop': 'apparel',
    'selfridges': 'apparel',
    'matalan': 'apparel',
    'revella': 'apparel',
    'looselyfitted': 'apparel',
    'fatface': 'apparel',
    'fittedstitch': 'apparel',
    'blackwells': 'books',
    'foyles': 'books',
    'ayarnstory': 'crafts',
    'brilliantbrushes': 'crafts',
    'cassart': 'crafts',
    'craftastic': 'crafts',
    'fivesensesart': 'crafts',
    'hobbylobby': 'crafts',
    'stitchbystitch': 'crafts',
    'theworks': 'crafts',
    'wool': 'crafts',
    'hobbycraft': 'crafts',
    'coffee#1': 'cafe',
    'costacoffee': 'cafe',
    'starbucks': 'cafe',
    'mamas&papas': 'children',
    'mothercare': 'children',
    'deliveroo': 'delivery',
    'justeat': 'delivery',
    'cex': 'electronics',
    'gamestation': 'electronics',
    'kewhouse': 'education',
    'lavenderprimary': 'education',
    'halifax': 'finance',
    'lbg': 'finance',
    'sainsbury': 'grocery',
    'sainsburylocal': 'grocery',
    'tesco': 'grocery',
    'cooplocal': 'grocery',
    'acutabove': 'hair and beauty',
    'barbieeboutique': 'hair and beauty',
    'remedypluscare': 'healthcare',
    'specsavers': 'healthcare',
    'universitycollegehospital': 'healthcare',
    'visionexpress': 'healthcare',
    'collectorcave': 'niche media',
    'hmv': 'niche media',
    'gapkids': 'niche apparel',
    'happydayshome': 'niche apparel',
    'millets': 'niche apparel',
    'mountainwarehouse': 'niche apparel',
    'northface': 'niche apparel',
    'head': 'niche sports',
    'rugbyfields': 'niche sports',
    'amazon': 'online shopping',
    'etsy': 'online shopping',
    'petscorner': 'pets',
    'lloydspharmacy': 'pharmacy',
    'boots': 'pharmacy',
    'kingsarms': 'pubs',
    'rose&crown': 'pubs',
    'thecrown': 'pubs',
    'frankie&bennies': 'restaurants',
    'grandunionbjj': 'sports',
    'jdsports': 'sports',
    'reebok': 'sports',
    'sportsdirect': 'sports',
    'blizzard': 'subscription',
    'disney': 'subscription',
    'mojangstudios': 'subscription',
    'netflix': 'subscription',
    'puregym': 'subscription',
    'squareonix': 'subscription',
    'xbox': 'subscription',
    'townhigh': 'other',
    'victoriapark': 'other'
}